package org.nuradinnur.eyeoftheherald.constant;

import java.util.HashMap;
import java.util.Map;

public enum Queues {
    CUSTOM(0),
    HOWLING_ABYSS_SNOWDOWN_SHOWDOWN_1V1(72),
    HOWLING_ABYSS_SNOWDOWN_SHOWDOWN_2V2(73),
    SUMMONERS_RIFT_HEXAKILL_6V6(75),
    SUMMONERS_RIFT_ULTRA_RAPID_FIRE(76),
    HOWLING_ABYSS_ONE_FOR_ALL_MIRROR_MODE(78),
    SUMMONERS_RIFT_COOP_VS_AI_ULTRA_RAPID_FIRE(83),
    TWISTED_TREELINE_HEXAKILL(98),
    BUTCHERS_BRIDGE_ALL_RANDOM_ALL_MIDDLE(100),
    SUMMONERS_RIFT_NEMESIS(310),
    SUMMONERS_RIFT_BLACK_MARKET_BRAWLERS(313),
    CRYSTAL_SCAR_DEFINITELY_NOT_DOMINION(317),
    SUMMONERS_RIFT_ALL_RANDOM(325),
    SUMMONERS_RIFT_DRAFT_PICK(400),
    SUMMONERS_RIFT_RANKED_SOLO(420),
    SUMMONERS_RIFT_BLIND_PICK(430),
    SUMMONERS_RIFT_RANKED_FLEX(440),
    HOWLING_ABYSS_ALL_RANDOM_ALL_MID(450),
    TWISTED_TREELINE_BLIND_PICK(460),
    TWISTED_TREELINE_RANKED_PICK(470),
    SUMMONERS_RIFT_BLOOD_MOON(600),
    COSMIC_RUINS_DARK_STAR_SINGULARITY(610),
    SUMMONERS_RIFT_CLASH(700),
    TWISTED_TREELINE_COOP_VS_AI_INTERMEDIATE(800),
    TWISTED_TREELINE_COOP_VS_AI_INTRO(810),
    TWISTED_TREELINE_COOP_VS_AI_BEGINNER(820),
    SUMMONERS_RIFT_COOP_VS_AI_INTRO(830),
    SUMMONERS_RIFT_COOP_VS_AI_BEGINNER(840),
    SUMMONERS_RIFT_COOP_VS_AI_INTERMEDIATE(850),
    SUMMONERS_RIFT_ALL_RANDOM_ULTRA_RAPID_FIRE(900),
    CRYSTAL_SCAR_ASCENSION(910),
    HOWLING_ABYSS_LEGEND_OF_THE_PORO_KING(920),
    SUMMONERS_RIFT_NEXUS_SIEGE(940),
    SUMMONERS_RIFT_DOOM_BOTS_VOTED_DIFFICULTY(950),
    SUMMONERS_RIFT_DOOM_BOTS_STANDARD_DIFFICULTY(960),
    VALORAN_CITY_PARK_STAR_GUARDIAN_INVASION_NORMAL(980),
    VALORAN_CITY_PARK_STAR_GUARDIAN_INVASION_ONSLAUGHT(990),
    SUBSTRUCTURE_43_OVERCHARGE(1000),
    SUMMONERS_RIFT_SNOW_ALL_RANDOM_ULTRA_RAPID_FIRE(1010),
    SUMMONERS_RIFT_ONE_FOR_ALL(1020),
    CRASH_SITE_ODYSSEY_EXTRACTION_INTRO(1030),
    CRASH_SITE_ODYSSEY_EXTRACTION_CADET(1040),
    CRASH_SITE_ODYSSEY_EXTRACTION_CREWMEMBER(1050),
    CRASH_SITE_ODYSSEY_EXTRACTION_CAPTAIN(1060),
    CRASH_SITE_ODYSSEY_EXTRACTION_ONSLAUGHT(1070),
    NEXUS_BLITZ_GAME_MODE_X(1200);

    private static final Map<Integer, Queues> lookup = new HashMap<>();
    private Integer key;

    static {
        for (Queues queue : Queues.values()) {
            lookup.put(queue.key, queue);
        }
    }

    Queues(int key) {
        this.key = key;
    }

    public static Queues getByValue(Integer value) {
        return lookup.get(value);
    }
}
